port: 7890
socks-port: 7891
mixed-port: 7892
allow-lan: true
mode: rule
log-level: info

dns:
  enable: true
  listen: "127.0.0.1:53"
  nameserver:
    - "1.1.1.1"
    - "192.168.0.1"
    - "8.8.8.8"

proxies:
  - name: "Moldova"
    type: trojan
    server: morse-stank-most.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Netherlands"
    type: trojan
    server: acre-cable-skip.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Norway"
    type: trojan
    server: copy-wifi-twins.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Portugal"
    type: trojan
    server: eats-rigor-judge.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Denmark"
    type: trojan
    server: wispy-crib-net.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Belgium"
    type: trojan
    server: chop-wrist-bud.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Canada"
    type: trojan
    server: both-cramp-banjo.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Ukraine"
    type: trojan
    server: keep-chess-self.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Poland"
    type: trojan
    server: tag-frown-lying.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Austria"
    type: trojan
    server: cushy-coil-chaos.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Hong Kong"
    type: trojan
    server: skate-whole-old.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Lithuania"
    type: trojan
    server: stem-entry-gala.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Italy"
    type: trojan
    server: boss-tutu-fled.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "France"
    type: trojan
    server: cadet-woven-march.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Russia"
    type: trojan
    server: slaw-hush-agile.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Germany"
    type: trojan
    server: share-basil-gills.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "USA"
    type: trojan
    server: patch-lint-hazel.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Israel"
    type: trojan
    server: bring-glove-shine.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Great Britain"
    type: trojan
    server: ankle-straw-untie.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Estonia"
    type: trojan
    server: tag-stump-ranch.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Greece"
    type: trojan
    server: stem-omen-area.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Switzerland"
    type: trojan
    server: crazy-grope-jeep.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Hungary"
    type: trojan
    server: sleep-boots-motor.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Romania"
    type: trojan
    server: guy-trace-lyric.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Turkey"
    type: trojan
    server: dried-chow-kite.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Spain"
    type: trojan
    server: strut-brisk-scope.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Serbia"
    type: trojan
    server: gong-aqua-rhyme.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Finland"
    type: trojan
    server: thaw-gut-jelly.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Sweden"
    type: trojan
    server: rash-scorn-glue.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Bulgaria"
    type: trojan
    server: cache-giver-wife.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Czechia"
    type: trojan
    server: bats-paper-chump.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Slovakia"
    type: trojan
    server: nacho-rerun-crepe.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Latvia"
    type: trojan
    server: dig-cage-gala.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Iceland"
    type: trojan
    server: trap-movie-power.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Japan"
    type: trojan
    server: lemon-gas-army.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Brazil"
    type: trojan
    server: wake-bagel-tall.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Slovenia"
    type: trojan
    server: lazy-work-poppy.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "Armenia"
    type: trojan
    server: upon-wimp-legal.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

  - name: "North Macedonia"
    type: trojan
    server: snarl-dish-cloth.stark-industries.solutions
    port: 443
    password: "8c9f9eda-17e5-4a36-a28a-f15903caa440"

proxy-groups:
  - name: "AUTO-SPEED"
    type: url-test
    proxies:
      # Первая тройка - основные рабочие лошадки
      - "Switzerland"
      - "Slovakia"
      - "Germany"

      # Восточная Европа
      - "Poland"
      - "Czechia"
      - "Hungary"
      - "Romania"
      - "Bulgaria"

      # Остальная Европа
      - "Netherlands"
      - "France"
      - "Austria"
      - "Belgium"
      - "Denmark"
      - "Spain"
      - "Portugal"
      - "Italy"
      - "Sweden"
      - "Norway"
      - "Finland"
      - "Greece"

      # Остальной мир
      - "Japan"
      - "Hong Kong"
      - "Canada"
      - "USA"
      - "Israel"
      - "Turkey"
      - "Brazil"

    url: "http://www.gstatic.com/generate_204"
    interval: 300
    tolerance: 50
  - name: "SELECTOR"
    type: select
    proxies:
      - "AUTO-SPEED"
      - "Switzerland"
      - "Slovakia"
      - "Germany"
      - "DIRECT"

rules:
  # Исключения для локальных адресов
  - DOMAIN,127.0.0.1,DIRECT
  - DOMAIN,localhost,DIRECT
  - DOMAIN,internal.domain,DIRECT

  # Исключения для сервисов разработки
  - DOMAIN-SUFFIX,github.com,DIRECT
  - DOMAIN-SUFFIX,githubusercontent.com,DIRECT
  - DOMAIN-SUFFIX,raw.githubusercontent.com,DIRECT
  - DOMAIN-SUFFIX,nixos.org,DIRECT
  - DOMAIN-SUFFIX,cache.nixos.org,DIRECT

  # Исключения для Reddit
  - DOMAIN-SUFFIX,reddit.com,DIRECT
  - DOMAIN-SUFFIX,reddit.map.fastly.net,DIRECT

  # Исключения для Yandex Cloud
  - DOMAIN-SUFFIX,stt.api.cloud.yandex.net,DIRECT
  - DOMAIN-SUFFIX,iam.api.cloud.yandex.net,DIRECT

  # Исключения для Rolder
  - DOMAIN-SUFFIX,rolder.app,DIRECT

  # Дефолтное правило в конце
  - MATCH,SELECTOR
